dist: trusty

env:
  - DOCKER_USERNAME=zhanghongqi
  - 

jobs:
  include:
    - stage: build docker image
      script:

      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        #- docker build -t travis-ci-build-stages-demo .
      - time docker build --target=builder -t django_example:dep .
      - docker images
      - docker tag django_example:dep $DOCKER_USERNAME/django_example
      - docker push $DOCKER_USERNAME/django_example
    - stage: deploy docker image
      script: docker run --rm $DOCKER_USERNAME/django_example ls -alt
    - script: docker run --rm $DOCKER_USERNAME/django_example ls -alt
#sudo: false
##
#services:
#  - docker
#
#before_script:
#  - sudo service docker stop
#  - if [ "$(ls -A /home/travis/docker)" ]; then echo "/home/travis/docker already set"; else sudo mv /var/lib/docker /home/travis/docker; fi
#  - sudo bash -c "echo 'DOCKER_OPTS=\"-H tcp://127.0.0.1:2375 -H unix:///var/run/docker.sock -g /home/travis/docker\"' > /etc/default/docker"
#  - sudo service docker start
#  - time docker build --target=builder -t django_example:dep .
#  - echo "afaafafafafasff***************"
#  - time docker build --cache-from django_example:dep -t django_example:final .
#
#script:
#  - echo "dont run "#docker run testenv
#
#before_cache:
#  - sudo service docker stop
#  - sudo chown -R travis ~/docker
#
#cache:
#  directories:
#    ~/docker
